import { Colors, FontSizes, Fonts, Spacing, BorderRadius, Shadow } from "@style/theme";
import { StyleSheet } from "react-native";

export const qrStyles = StyleSheet.create({
  // ─── Container (docent camera view) ───────────────────────────
  container: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000",
  },
  camera: {
    flex: 1,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 48,
  },
  scanFrame: {
    position: "absolute",
    top: "25%",
    left: "20%",
    right: "20%",
    aspectRatio: 1,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.6)",
    borderRadius: BorderRadius.lg,
    backgroundColor: "transparent",
  },
  scanFrameCornerTL: {
    position: "absolute",
    top: -2,
    left: -2,
    width: 30,
    height: 30,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderColor: Colors.primary["400"],
    borderRadius: 4,
  },
  scanFrameCornerTR: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 30,
    height: 30,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderColor: Colors.primary["400"],
    borderRadius: 4,
  },
  scanFrameCornerBL: {
    position: "absolute",
    bottom: -2,
    left: -2,
    width: 30,
    height: 30,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderColor: Colors.primary["400"],
    borderRadius: 4,
  },
  scanFrameCornerBR: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 30,
    height: 30,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderColor: Colors.primary["400"],
    borderRadius: 4,
  },
  overlayText: {
    fontSize: FontSizes.default,
    fontFamily: Fonts.semiBold,
    color: Colors.white,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    overflow: "hidden",
  },
  messageBox: {
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.lg,
    maxWidth: "85%",
  },
  messageBoxSuccess: {
    backgroundColor: Colors.success["500"],
  },
  messageBoxError: {
    backgroundColor: Colors.error["600"],
  },
  messageText: {
    color: Colors.white,
    fontFamily: Fonts.semiBold,
    fontSize: FontSizes.sm,
    textAlign: "center",
  },
  scanAgainButton: {
    position: "absolute",
    bottom: 100,
    alignSelf: "center",
    backgroundColor: Colors.primary["500"],
    paddingHorizontal: Spacing["2xl"],
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.full,
    ...Shadow.md,
  },
  scanAgainText: {
    color: Colors.white,
    fontFamily: Fonts.semiBold,
    fontSize: FontSizes.default,
  },
  // ─── Student QR display ─────────────────────────────────────────
  title: {
    fontSize: FontSizes.xxxl,
    fontFamily: Fonts.bold,
    textAlign: "center",
    marginBottom: Spacing.sm,
  },
  qrWrapper: {
    padding: Spacing.xl,
    borderRadius: BorderRadius.xl,
    ...Shadow.lg,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: Spacing.xl,
  },
  description: {
    fontSize: FontSizes.sm,
    fontFamily: Fonts.regular,
    textAlign: "center",
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing["2xl"],
  },
  countdownContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    backgroundColor: "rgba(0,0,0,0.06)",
  },
  countdownText: {
    fontSize: FontSizes.sm,
    fontFamily: Fonts.semiBold,
  },
  message: {
    fontSize: FontSizes.default,
    fontFamily: Fonts.regular,
    textAlign: "center",
    paddingHorizontal: Spacing.xl,
    color: Colors.gray[600],
  },
  permissionButton: {
    marginTop: Spacing.md,
    backgroundColor: Colors.primary["500"],
    paddingHorizontal: Spacing["2xl"],
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.full,
    ...Shadow.sm,
  },
  permissionButtonText: {
    color: Colors.white,
    fontFamily: Fonts.semiBold,
    fontSize: FontSizes.default,
  },
});
